module.exports = {
  'access-log': require('access-log.js'),
  'access': require('access.js'),
  'error': require('error.js'),
  'file-name': require('file-name.js'),
  'id': require('id.js'),
  'json': require('json.js'),
  'level': require('level.js'),
  'map': require('map.js'),
  'message': require('message.js'),
  'raw-json': require('raw-json.js'),
  'scope': require('scope.js'),
  'summary': require('summary.js'),
  'time-diff-init': require('time-diff-init.js'),
  'time-diff-scope': require('time-diff-scope.js'),
  'zipkin-level': require('zipkin-level.js'),
}
